import React from 'react';

const box = { background: '#0f172a', border: '1px solid #1e293b', borderRadius: 12, padding: 18, marginBottom: 16 };
function Section({ title, color = '#334155', children }) { return <section style={{ ...box, borderLeft: `4px solid ${color}` }}><h3 style={{ margin: '0 0 12px' }}>{title}</h3><div style={{ color: '#cbd5e1', fontSize: 12.5, lineHeight: 1.7 }}>{children}</div></section>; }
function Cards({ items }) { return <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 10 }}>{items.map((item) => <div key={item.title} style={{ background: '#111827', border: '1px solid #1e293b', borderTop: `3px solid ${item.color}`, borderRadius: 9, padding: 12 }}><div style={{ color: item.color, fontWeight: 800, marginBottom: 5 }}>{item.title}</div><div style={{ color: '#94a3b8', fontSize: 11.5, lineHeight: 1.6 }}>{item.text}</div></div>)}</div>; }

export default function Guide() {
  return <div>
    <div style={{ background: 'linear-gradient(135deg,#1e1b4b,#0f172a)', border: '1px solid #4c1d95', borderRadius: 16, padding: 28, marginBottom: 18 }}><div style={{ color: '#a78bfa', fontWeight: 900, fontSize: 11 }}>SWINGLAB · GUIDA OPERATIVA</div><h1 style={{ margin: '8px 0 12px' }}>Trading multi-agente, Max Strategy e Crash Deploy</h1><p style={{ margin: 0, color: '#cbd5e1', lineHeight: 1.7 }}>SwingLab analizza 300 titoli e 11 settori. La strategia Legacy opera sul paper account. Max Strategy v1.5.2 lavora in Shadow Mode e non invia ordini.</p></div>
    <Section title="Stato attuale" color="#22c55e"><Cards items={[{ title: 'Universo 300', color: '#3b82f6', text: 'Gate STALE_OR_DELISTED oltre 7 giorni. EQR è attualmente bloccato.' },{ title: 'Legacy live paper', color: '#22c55e', text: 'Alpha, Risk, Executor e APM gestiscono la strategia operativa corrente.' },{ title: 'Max live OFF', color: '#8b5cf6', text: 'Piani, trigger e sizing sono simulati. Executor e APM non ricevono decisioni Max.' },{ title: 'Validazione', color: '#06b6d4', text: 'Snapshot point-in-time, MFE, MAE e rendimenti a 5, 10 e 20 sedute.' }]} /></Section>
    <Section title="Pipeline degli agenti" color="#8b5cf6"><ol><li><strong>MacroAnalyst</strong>: regime ed esposizione.</li><li><strong>AlphaStrategist</strong>: candidati Legacy e Alpha Shadow Max.</li><li><strong>RiskManager</strong>: sizing reale Legacy e Risk Shadow Max.</li><li><strong>APM</strong>: gestione delle posizioni esistenti.</li><li><strong>Executor</strong>: ordini approvati negli orari consentiti.</li></ol></Section>
    <Section title="Max Strategy v1.5.2" color="#8b5cf6"><p>La Max Strategy non compra ciò che è semplicemente sceso. Cerca arresto del markdown, accumulazione e conferma.</p><Cards items={[{ title: 'Weekly', color: '#8b5cf6', text: 'POC maestro, rounding, neck, discendente, target e fase del ciclo.' },{ title: 'Daily', color: '#3b82f6', text: 'Conferma breakout, volume, candela, trigger e maximum entry.' },{ title: '4H', color: '#06b6d4', text: 'Rifinisce breakout, retest e stop. Se manca viene usato il Daily fallback.' }]} /><div style={{ marginTop: 12, background: '#111827', borderRadius: 8, padding: 12, fontFamily: 'monospace', fontSize: 11 }}>DETECTED → ARMED → TRIGGERED → CONFIRMED_4H / CONFIRMED_DAILY<br />WAIT_RETEST se il prezzo è troppo esteso · BLOCKED se intervengono i gate</div></Section>
    <Section title="Gate Max" color="#ef4444"><Cards items={[{ title: 'Falling Knife', color: '#ef4444', text: 'Nuovi minimi Weekly e momentum negativo bloccano il trade.' },{ title: 'Mature Markup', color: '#f97316', text: 'Nessun ingresso Max tardivo sui titoli già vicini ai massimi.' },{ title: 'Maximum Entry', color: '#eab308', text: 'Il sistema non insegue breakout troppo estesi e attende il retest.' },{ title: 'Data Quality', color: '#64748b', text: 'Ticker stale, delistati o incoerenti vengono esclusi e ripuliti.' }]} /></Section>
    <Section title="Shadow Mode" color="#06b6d4"><ul><li>Alpha Shadow: WOULD_ARM, WOULD_BUY, WOULD_WAIT, WOULD_REJECT.</li><li>Risk Shadow: WOULD_APPROVE, WOULD_REDUCE, WOULD_REJECT.</li><li>Ordini Max live OFF.</li><li>Registro max_strategy_signals con outcome point-in-time.</li></ul></Section>
    <Section title="Legacy, APM e Crash Deploy" color="#22c55e"><Cards items={[{ title: 'APM 30/30/25', color: '#22c55e', text: 'Scale-out sulla quantità residua, runner finale e holding minimo 24 ore.' },{ title: 'Profit floors', color: '#8b5cf6', text: 'Floor 0%, 3% e 8% coordinati con gli stop software.' },{ title: 'APM EXIT', color: '#ef4444', text: 'Richiede almeno 3 fattori negativi per evitare uscite premature.' },{ title: 'Crash Deploy', color: '#ef4444', text: 'Strategia indipendente e contrarian su SPY durante drawdown importanti.' }]} /></Section>
    <Section title="Pagina Stock" color="#3b82f6"><p>Carica fino a 350 asset. Offre ricerca, filtri Max, ordinamento, vista compatta e caricamento progressivo. Il dettaglio mostra piano Max, Weekly, Daily, 4H, trigger e invalidazione. TradingView dispone di schermo intero e usa soltanto la SMA 200.</p></Section>
    <Section title="Roadmap" color="#f97316"><ol><li>Mantenere l’universo a 300 e monitorare Render.</li><li>Raccogliere almeno 30-50 segnali Max attivati.</li><li>Creare max_entry_plans persistenti senza ordini.</li><li>Valutare paper execution Max con size ridotta.</li><li>Integrare poi target strutturali e APM Max.</li><li>Migrare in futuro a Render Cron Job sequenziale con lock MongoDB.</li></ol></Section>
  </div>;
}
