export const TIPS = {
  sharpe: "Rendimento per unità di rischio totale. >1 buono, >2 ottimo. Con pochi trade (<30) è poco affidabile.",
  sortino: "Come Sharpe ma penalizza solo le discese (rischio 'cattivo'). >1,5 buono. Con pochi trade è gonfiato.",
  expectancy: "Guadagno medio atteso per ogni trade. Si legge PER TRADE, non si moltiplica per il numero di operazioni.",
  profit_factor: "Dollari vinti diviso dollari persi. 1,33 = guadagni 1,33$ per ogni 1$ perso. >1,5 ottimo.",
  max_drawdown: "La peggior caduta dal picco massimo del capitale. Più vicino a 0 = meglio.",
  win_rate: "% di operazioni chiuse in profitto (conta ogni scale-out come operazione separata).",
  total_pnl_pct: "Rendimento reale = profitto in $ diviso capitale iniziale. NON è la somma delle % dei trade.",
  total_pnl_dollar: "Profitto/perdita totale in dollari sul capitale.",
  win_rate_execution: "Conta ogni riga di vendita, incluse le tranche T1/T2/T3. Tende a essere gonfiato.",
  win_rate_position: "Raggruppa gli scale-out: 1 posizione = 1 risultato. È il dato più onesto.",
  win_rate_dollar: "Pesato sul capitale mosso: i target grandi contano più dei piccoli.",
  kelly_raw: "Frazione di capitale suggerita dalla formula Kelly pura. Enorme e rischiosa: mai usarla intera.",
  kelly_fractional: "Kelly ridotto per sicurezza (dipende dal profilo di rischio: Moderato 0.20, Aggressivo 0.25).",
  dps_multiplier: "Dynamic Position Sizing: amplifica o riduce la size in base a R/R, ML e confluence del trade.",
  regime_multiplier: "Riduce l'esposizione fuori dai mercati BULL (NEUTRAL 0.6x, BEAR 0.3x). Protezione macro.",
  position_size_base: "% base di capitale per posizione, GIÀ moltiplicata per il regime di mercato.",
  risk_per_trade: "Quanti dollari perdi se scatta lo stop loss su questa posizione.",
};
